# books/forms.py

from django import forms
from .models import Book, Tag

class BookForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        required=False,
        widget=forms.SelectMultiple(attrs={'class': 'tag-select'})
    )

    class Meta:
        model = Book
        exclude = ['call_number']  # Exclude autogenerated call_number
        # If you want to be explicit, you can use 'fields' instead:
        # fields = ['title', 'author', ... , 'tags']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.all()
        if self.instance and self.instance.pk:
            self.fields['tags'].initial = self.instance.tags.all()

    def clean_tags(self):
        tags = self.cleaned_data['tags']
        if len(tags) > 10:
            raise forms.ValidationError("You can select up to 10 tags.")
        return tags

    zine_code = forms.CharField(
        max_length=100,
        required=True,
        label="GCL Zine Code",
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter your secret code...',
        })
    )

    def save(self, commit=True):
        book = super().save(commit=False)
        if commit:
            book.save()
            self.save_m2m()
        return book