# Generated by Django 5.2.3 on 2025-07-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('type_code', models.CharField(choices=[('Da', 'Dark'), ('Fo', 'Folk'), ('Na', 'Nature'), ('El', 'Elder')], max_length=2)),
                ('class_code', models.CharField(choices=[('GRM', 'Grimoire'), ('FLD', 'Field Guide'), ('ESO', 'Esoterica'), ('BST', 'Bestiary'), ('RTL', 'Rituals'), ('PTN', 'Potions'), ('MKN', 'Machines'), ('RNS', 'Runes'), ('SMN', 'Summoning'), ('CRM', 'Charms and Enchantments'), ('AST', 'Astrology'), ('DVN', 'Divination'), ('HRB', 'Herbarium'), ('PRL', 'Portal Book')], max_length=3)),
                ('call_number', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='books.tag')),
            ],
        ),
    ]
