# Generated by Django 5.2.3 on 2025-07-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
