# Generated by Django 5.2.3 on 2025-07-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_class_code_book_book_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_first_name',
        ),
        migrations.AddField(
            model_name='book',
            name='author_last_name',
            field=models.CharField(default=' author', max_length=200),
            preserve_default=False,
        ),
    ]
