# Generated by Django 5.2.3 on 2025-07-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_author_book_author_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='entry_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
