# Generated by Django 5.2.3 on 2025-07-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_entry_number_alter_book_author_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
