# Generated by Django 5.2.3 on 2025-07-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_title_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='librarian',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
