# Generated by Django 5.2.3 on 2025-07-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_anonymous',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
