# Generated by Django 5.2.3 on 2025-07-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_author_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='magic_category',
            field=models.CharField(choices=[('DA', 'Dark'), ('FO', 'Folk'), ('NA', 'Nature'), ('EL', 'Elder')], max_length=2),
        ),
    ]
