# Generated by Django 5.2.3 on 2025-07-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_magic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
