# Generated by Django 5.2.3 on 2025-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('GRM', 'Grimoire'), ('FLD', 'Field Guide'), ('ESO', 'Esoterica'), ('BST', 'Bestiary'), ('RTL', 'Rituals'), ('PTN', 'Potions'), ('MKN', 'Machines'), ('RNS', 'Runes'), ('SMN', 'Summoning'), ('ENC', 'Enchantments'), ('AST', 'Astrology'), ('DVN', 'Divination'), ('HRB', 'Herbarium'), ('PRL', 'Portal Book')], max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='entry_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
